member/api/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

from member.api.views import MemberListAPI, MemberDetailAPI, \
    MemberDetailReadingOnly, MemberDetailBan, MemberMyDetailAPI

urlpatterns = patterns('',
                       url(r'^$', MemberListAPI.as_view(), name='api-member-list'),
                       url(r'^mon-profil/$', MemberMyDetailAPI.as_view(), name='api-member-profile'),
                       url(r'^(?P<pk>[0-9]+)/$', MemberDetailAPI.as_view(), name='api-member-detail'),
                       url(r'^(?P<pk>[0-9]+)/lecture-seule/$', MemberDetailReadingOnly.as_view(),
                           name='api-member-read-only'),
                       url(r'^(?P<pk>[0-9]+)/ban/$', MemberDetailBan.as_view(), name='api-member-ban'),
                       )

member/urls.py
# coding: utf-8

from django.conf.urls import patterns, url, include

from member.views import MemberList, MemberDetail, UpdateMember, UpdatePasswordMember, \
    UpdateUsernameEmailMember, RegisterView, SendValidationEmailView

urlpatterns = patterns('',
                       #list
                       url(r'^$', MemberList.as_view(), name='member-list'),

                       #details
                       url(r'^voir/(?P<user_name>.+)/$', MemberDetail.as_view(), name='member-detail'),

                       #modification
                       url(r'^parametres/profil/$', UpdateMember.as_view(), name='update-member'),
                       url(r'^parametres/compte/$', UpdatePasswordMember.as_view(), name='update-password-member'),
                       url(r'^parametres/user/$', UpdateUsernameEmailMember.as_view(), name='update-username-email-member'),

                       #moderation
                       url(r'^profil/karmatiser/$', 'member.views.modify_karma'),
                       url(r'^profil/modifier/(?P<user_pk>\d+)/$', 'member.views.modify_profile'),
                       url(r'^parametres/mini_profil/(?P<user_name>.+)/$', 'member.views.settings_mini_profile'),
                       url(r'^profil/multi/(?P<ip_address>.+)/$', 'member.views.member_from_ip'),

                       #user rights
                       url(r'^profil/promouvoir/(?P<user_pk>\d+)/$', 'member.views.settings_promote'),

                       #membership
                       url(r'^connexion/$', 'member.views.login_view'),
                       url(r'^deconnexion/$', 'member.views.logout_view'),
                       url(r'^inscription/$', RegisterView.as_view(), name='register-member'),
                       url(r'^reinitialisation/$', 'member.views.forgot_password'),
                       url(r'^validation/$', SendValidationEmailView.as_view(), name='send-validation-email'),
                       url(r'^new_password/$', 'member.views.new_password'),
                       url(r'^activation/$', 'member.views.active_account'),
                       url(r'^envoi_jeton/$', 'member.views.generate_token_account'),
                       url(r'^desinscrire/valider/$', 'member.views.unregister'),
                       url(r'^desinscrire/avertissement/$', 'member.views.warning_unregister')
                       )

# API
urlpatterns += patterns('',
                        url(r'^oauth2/', include('oauth2_provider.urls', namespace='oauth2_provider')),
                        url(r'^api/', include('member.api.urls')),
                        )

member/models.py
# coding: utf-8

from datetime import datetime
from member.conf import settings
from django.db import models
from hashlib import md5
from django.http import HttpRequest
from django.contrib.sessions.models import Session
from django.contrib.auth import logout
import os

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.dispatch import receiver
from django.contrib.sites.models import Site

import pygeoip
from .managers import ProfileManager
from importlib import import_module


class Profile(models.Model):
    """
    A user profile. Complementary data of standard Django `auth.user`.
    """

    class Meta:
        verbose_name = 'Profil'
        verbose_name_plural = 'Profils'
        permissions = (
            ("moderation", u"Moderate membre"),
            ("show_ip", u"Show member's Ip Adress"),
        )

    # Link with standard user is a simple one-to-one link, as recommended in official documentation.
    # See https://docs.djangoproject.com/en/1.6/topics/auth/customizing/#extending-the-existing-user-model
    user = models.OneToOneField(
        User,
        verbose_name='User',
        related_name="profile")

    last_ip_address = models.CharField(
        'IP Adress',
        max_length=39,
        blank=True,
        null=True)

    site = models.CharField('Web site', max_length=2000, blank=True)
    show_email = models.BooleanField('Show email adress on public',
                                     default=False)

    avatar_url = models.CharField(
        'Avatar url', max_length=2000, null=True, blank=True
    )

    biography = models.TextField('Biography', blank=True)

    karma = models.IntegerField('Karma', default=0)

    sign = models.TextField('Sign', max_length=250, blank=True)

    show_sign = models.BooleanField('Show signs', default=True)

    # TODO: Change this name. This is a boolean: "true" is "hover" or "click" ?!
    hover_or_click = models.BooleanField('Hover or clic ?', default=False)

    email_for_answer = models.BooleanField('Envoyer pour les réponse MP', default=False)

    can_read = models.BooleanField('Possibilité de lire', default=True)
    end_ban_read = models.DateTimeField(
        'Fin d\'interdiction de lecture',
        null=True,
        blank=True)

    can_write = models.BooleanField('Possibilité d\'écrire', default=True)
    end_ban_write = models.DateTimeField(
        'Fin d\'interdiction d\'ecrire',
        null=True,
        blank=True)

    last_visit = models.DateTimeField(
        'Date de dernière visite',
        null=True,
        blank=True)

    objects = ProfileManager()
    _permissions = {}

    def __unicode__(self):
        return self.user.username

    def is_private(self):
        """
        Check if the user belong to the bot's group or not

        :return: ``True`` if user belong to the bot's group, ``False`` else.

        :rtype: bool
        """
        user_groups = self.user.groups.all()
        user_group_names = [g.name for g in user_groups]
        return settings.ZDS_MEMBER['bot_group'] in user_group_names

    def get_absolute_url(self):
        """Absolute URL to the profile page."""
        return reverse('member-detail', kwargs={'user_name': self.user.username})

    def get_city(self):
        """
        Uses geo-localization to get physical localization of a profile through its last IP address.
        This works relatively good with IPv4 addresses (~city level), but is very imprecise with IPv6 or exotic internet
        providers.

        :return: The city and the country name of this profile.

        :rtype: str
        """
        # FIXME: this test to differentiate IPv4 and IPv6 addresses doesn't work, as IPv6 addresses may have length < 16
        # Example: localhost ("::1"). Real test: IPv4 addresses contains dots, IPv6 addresses contains columns.
        if len(self.last_ip_address) <= 16:
            gic = pygeoip.GeoIP(
                os.path.join(
                    settings.GEOIP_PATH,
                    'GeoLiteCity.dat'))
        else:
            gic = pygeoip.GeoIP(
                os.path.join(
                    settings.GEOIP_PATH,
                    'GeoLiteCityv6.dat'))

        geo = gic.record_by_addr(self.last_ip_address)

        if geo is not None:
            return u'{0}, {1}'.format(geo['city'], geo['country_name'])
        return ''

    def get_avatar_url(self):
        """Get the avatar URL for this profile.
        If the user has defined a custom URL, use it.
        If not, use Gravatar.

        :return: The avatar URL for this profile

        :rtype: str
        """
        if self.avatar_url:
            current_site = Site.objects.get_current()
            if self.avatar_url.startswith(settings.MEDIA_URL):
                return u"{}{}".format(current_site.domain, self.avatar_url)
            else:
                return self.avatar_url
        else:
            return 'https://secure.gravatar.com/avatar/{0}?d=identicon'.format(
                md5(self.user.email.lower().encode("utf-8")).hexdigest())

    def can_read_now(self):
        """
        Check if you can read a web site content as user.
        If you can't read, you can't login on website.
        This happens when you have been banned (temporarily or definitively)

        :return: ``False`` if you are banned, ``True`` else.

        :rtype: bool
        """
        if self.user.is_authenticated:
            if self.user.is_active:
                if self.end_ban_read:
                    return self.can_read or (
                        self.end_ban_read < datetime.now())
                else:
                    return self.can_read
            else:
                return False

    def can_write_now(self):
        """
        Check if you can write something on a web site as user.
        This happens when you have been reading only (temporarily or definitively)

        :return: ``False`` if you are read only, ``True`` else.

        :rtype: bool
        """
        if self.user.is_active:
            if self.end_ban_write:
                return self.can_write or (self.end_ban_write < datetime.now())
            else:
                return self.can_write
        else:
            return False


@receiver(models.signals.post_delete, sender=User)
def auto_delete_token_on_unregistering(sender, instance, **kwargs):
    """
    This signal receiver deletes forgotten password tokens and registering tokens for the un-registering user;
    """
    TokenForgotPassword.objects.filter(user=instance).delete()
    TokenRegister.objects.filter(user=instance).delete()


class TokenForgotPassword(models.Model):
    """
    When a user forgot its password, the website sends it an email with a token (embedded in a URL).
    If the user has the correct token, it can choose a new password on the dedicated page.
    This model stores the tokens for the users that have forgot their passwords, with an expiration date.
    """
    class Meta:
        verbose_name = 'Token de mot de passe oublié'
        verbose_name_plural = 'Tokens de mots de passe oubliés'

    user = models.ForeignKey(User, verbose_name='Utilisateur', db_index=True)
    token = models.CharField(max_length=100, db_index=True)
    date_end = models.DateTimeField('Date de fin')

    def get_absolute_url(self):
        """
        :return: The absolute URL of the "New password" page, including the correct token.
        """
        return reverse('member.views.new_password') + '?token={0}'.format(self.token)

    def __unicode__(self):
        return u"{0} - {1}".format(self.user.username, self.date_end)


class TokenRegister(models.Model):
    """
    On registration, a token is send by mail to the user. It must use this token (by clicking on a link) to activate its
    account (and prove the email address is correct) and connect itself.
    This model stores the registration token for each user, with an expiration date.
    """
    class Meta:
        verbose_name = 'Token d\'inscription'
        verbose_name_plural = 'Tokens  d\'inscription'

    user = models.ForeignKey(User, verbose_name='Utilisateur', db_index=True)
    token = models.CharField(max_length=100, db_index=True)
    date_end = models.DateTimeField('Date de fin')

    def get_absolute_url(self):
        """
        :return: the absolute URL of the account validation page, including the token.
        """
        return reverse('member.views.active_account') + '?token={0}'.format(self.token)

    def __unicode__(self):
        return u"{0} - {1}".format(self.user.username, self.date_end)


class Ban(models.Model):
    """
    This model stores all sanctions (not only bans).
    It stores sanctioned user, the moderator, the type of sanctions, the reason and the date.
    Note this stores also un-sanctions.
    """

    class Meta:
        verbose_name = 'Sanction'
        verbose_name_plural = 'Sanctions'

    user = models.ForeignKey(User, verbose_name='Sanctionné', db_index=True)
    moderator = models.ForeignKey(User, verbose_name='Moderateur',
                                  related_name='bans', db_index=True)
    type = models.CharField('Type', max_length=80, db_index=True)
    text = models.TextField('Explication de la sanction')
    pubdate = models.DateTimeField(
        'Date de publication',
        blank=True,
        null=True, db_index=True)

    def __unicode__(self):
        return u"{0} - ban : {1} ({2}) ".format(self.user.username, self.text, self.pubdate)


class KarmaNote(models.Model):
    """
    A karma note is a tool for staff to store data about a member.
    Data are:

    - A note (negative values are bad)
    - A comment about the member
    - A date

    This helps the staff to react and stores history of stupidities of a member.
    """
    class Meta:
        verbose_name = 'Note de karma'
        verbose_name_plural = 'Notes de karma'

member/templates/member/base.html
{% extends "base.html" %}
{% load i18n %}


{% block title_base %}
    &bull; {% trans "Membres" %}
{% endblock %}



{% block mobile_title %}
    {% trans "Membres" %}
{% endblock %}



{% block breadcrumb_base %}
    <li><a href="{% url 'member-list' %}">{% trans "Membres" %}</a></li>
{% endblock %}



{% block sidebar %}
    <aside class="sidebar mobile-menu-hide">
        {% block sidebar_actions %}{% endblock %}
    </aside>
{% endblock %}

member/templates/member/index.html
{% extends "member/base.html" %}
{% load i18n %}


{% block title %}
    {% trans "Liste des membres" %}
{% endblock %}



{% block breadcrumb %}
    <li>{% trans "Liste des membres" %}</li>
{% endblock %}



{% block headline %}
    {% trans "Liste des membres" %}
{% endblock %}



{% block content %}
    <p>
        {% trans "Sur cette page vous pourrez trouver la liste des membres inscrits au site (actuellement" %} {{ paginator.count }} {% trans "membres" %}).
    </p>


    {% include "misc/paginator.html" with position="top" %}

    <div class="authors">
        <ul>
            {% for member in members %}
                <li>
                    {% include "misc/member_item.part.html" with avatar=True %}
                </li>
            {% empty %}
                <li>
                    {% trans "Aucun membre pour le moment." %}
                </li>
            {% endfor %}
        </ul>
    </div>

    {% include "misc/paginator.html" with position="bottom" %}
{% endblock %}

member/templates/member/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block title %}
    {% trans "Connexion" %}
{% endblock %}



{# No sidebar on this page #}
{% block body_class %}{% trans "no-sidebar" %}{% endblock %}
{% block sidebar %}{% endblock %}



{% block breadcrumb %}
    <li>{% trans "Connexion" %}</li>
{% endblock %}



{% block content_out %}
    <section class="content-wrapper">
        {% if not user.is_authenticated %}
            {% if error %}
                <div class="alert-box warning">
                    {{ error }}
                </div>
            {% endif %}
            <p class="alert-box success">
                {% url "register-member" as url_register %}
                {% blocktrans %}
                    Si vous n'avez pas de compte, vous pouvez <a href="{{url_register}}" >vous inscrire</a>.
                {% endblocktrans %}
            </p>

            <div>
                <div class="content-col-2">
                    <h2>{% trans "Connexion classique" %}</h2>
                    {% crispy form %}
                    <p>
                        <a href="{% url "member.views.forgot_password" %}">
                            {% trans "Mot de passe oublié ?" %}
                        </a>
                    </p>
                    <p>
                        <a href="{% url "send-validation-email" %}">
                            {% trans "Vous n'avez pas reçu le courriel d'activation ?" %}
                        </a>
                    </p>
                </div>
            </div>
        {% else %}
            <h1>{% trans "Connexion" %}</h1>

            <p class="alert-box error">
                {% trans "Vous êtes déjà connecté" %}.
            </p>
        {% endif %}
    </section>
{% endblock %}

member/templates/member/profile.html
{% extends "member/base.html" %}

{% load emarkdown %}
{% load email_obfuscator %}
{% load date %}
{% load profile %}
{% load crispy_forms_tags %}
{% load i18n %}



{% block title %}
    {{ usr.username }}
{% endblock %}



{% block body_class %}content-cols{% endblock %}



{% block breadcrumb %}
    <li>{{ usr.username }}</li>
{% endblock %}



{% block content_out %}
    <section class="content-col-2">
        <h1 id="infos-generales">
            {% trans "Profil de" %} {{ usr.username }}
        </h1>

        <div class="member-card">
            <div class="member-avatar">
                <img src="{{ profile.get_avatar_url }}" alt="" class="avatar">

                {% include 'misc/badge.part.html' with member=usr %}
            </div>

            <ul class="member-infos">
                {% if not profile.is_private %}
                    <li>
                        {% trans "Inscrit" %} {{ usr.date_joined|format_date:True }}
                    </li>
                    <li>
                        {% trans "Dernière visite sur le site" %} :
                            {% if profile.last_visit %}
                                {{ profile.last_visit|format_date:True }}
                            {% else %}
                                {% trans "ne s'est jamais connecté(e)" %}
                            {% endif %}
                    </li>
                {% else %}
                    <li>
                        {% trans "Ce membre est un compte d'administration" %}
                    </li>
                {% endif %}
                {% if perms.member.show_ip %}
                    <li>
                        {% trans "Dernière IP" %} : <a href="{% url "member.views.member_from_ip" profile.last_ip_address %}">{{ profile.last_ip_address }}</a>
                    </li>
                    <li>
                        {{ profile.get_city }}
                    </li>
                {% endif %}
            </ul>
        </div>


        <hr class="clearfix" />


        <ul class="member-social">
            {% if profile.show_email and user.is_authenticated %}
                <li>
                    {% trans "E-mail" %} : {{ usr.email|obfuscate_mailto }}
                </li>
            {% endif %}

            {% if profile.site %}
                <li>
                    {% trans "Site web" %} : <a href="{{ profile.site }}">{{ profile.site }}</a>
                </li>
            {% endif %}
        </ul>

        {% if perms.member.change_profile and not profile.is_private %}
            <div>
                {% trans "Remarques sur cet utilisateur" %} ({{ profile.karma }}) :
                <ul>
                {% if karmanotes.count > 0 %}
                    {% for note in karmanotes %}
                        <li><strong>{{ note.value }}</strong> {{ note.create_at|format_date:True }} {% trans "par" %} {{ note.staff.username }} : {{ note.comment }}</li>
                    {% endfor %}
                {% else %}
                    <li>{% trans "Cet utilisateur n'a reçu aucune remarque" %}</li>
                {% endif %}
                </ul>
                <a href="#karmatiser-modal" class="open-modal">{% trans "Ajouter une remarque" %}</a>
                <div id="karmatiser-modal" class="modal modal-big">
                    {% crispy karmaform %}
                </div>
            </div>
        {% endif %}

        {% if profile.sign %}
            <h2 id="signature">{% trans "Signature" %}</h2>
            {{ profile.sign|emarkdown_inline }}
        {% endif %}


        {% if topics %}
            <h2 id="derniers-sujets">{% trans "Derniers sujets créés" %}</h2>
            <div class="topic-list navigable-list" itemscope itemtype="http://schema.org/ItemList">
                {% for topic in topics %}
                    {% include "forum/includes/topic_row.part.html" %}
                {% endfor %}
            </div>
        {% endif %}
    </section>


    {% if profile.biography %}
        <hr class="clearfix" />
        <section class="full-content-wrapper without-margin article-content">
            <h2 id="biographie">{% trans "Biographie" %}</h2>
            {{ profile.biography|emarkdown }}
        </section>
    {% endif %}

    {% if stats_filename and perms.member.change_profile %}
        <hr class="clearfix" />
        <section class="full-content-wrapper without-margin">
            <h2 id="activity">{% trans "Activité" %}</h2>
            <figure>
                {% autoescape off %}
                    {{stats_filename}}
                {% endautoescape %}
            </figure>
        </section>
    {% endif %}


{% endblock %}



{% block sidebar_actions %}
    {% if user.is_authenticated %}
        {% if profile.user == user or perms.member.change_profile %}
            <div>
                {% if profile.user == user %}
                    <a href="{% url "update-member" %}" class="new-btn ico-after gear blue">
                        {% trans "Paramètres" %} <span class="wide">{% trans "de mon compte" %}</span>
                    </a>
                {% else %}
                    <a href="{% url "member.views.settings_mini_profile" profile.user.username %}" class="new-btn ico-after edit blue">
                        {% trans "Modifier le profil" %}
                    </a>
                {% endif %}
                {% if perms.member.super_user %}
                    <a href="{% url "member.views.settings_promote" profile.user.pk %}" class="new-btn ico-after edit gear blue">
                        {% trans "Promouvoir" %}
                    </a>
                {% endif %}
            </div>
        {% endif %}
    {% endif %}

    <div class="mobile-menu-bloc mobile-all-links" data-title='{% trans "Accès rapide" %}'>
        <h3>{% trans "Accès rapide" %}</h3>
        <ul>
            <li>
                <a href="#infos-generales">
                    {% trans "Informations générales" %}
                </a>
            </li>
            {% if profile.sign %}
                <li>
                    <a href="#signature">
                        {% trans "Signature" %}
                    </a>
                </li>
            {% endif %}
            {% if profile.biography %}
                <li>
                    <a href="#biographie">
                        {% trans "Biographie" %}
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>


    {% if perms.member.change_profile and profile.user.is_active %}
        <div class="mobile-menu-bloc mobile-all-links" data-title='{% trans "Modération" %}'>
            <h3>{% trans "Modération" %}</h3>
            {% if not profile.is_private and usr != user %}
            <h4>{% trans "Sanctions" %}</h4>
            <ul>
                {% if profile.can_write_now %}
                    <li>
                        <a href="#ls-temp-{{ profile.pk }}" class="open-modal">
                            {% trans "Lecture seule temporaire" %}
                        </a>
                        <form action="{% url "member.views.modify_profile" profile.user.pk %}" method="post" id="ls-temp-{{ profile.pk }}" class="modal modal-big">
                            <p>
                                {% blocktrans %}
                                    Pour quelle raison souhaitez-vous mettre ce membre en lecture seule <em>temporairement</em> ?
                                {% endblocktrans %}
                            </p>
                            <input type="text" name="ls-text" class="expand" placeholder="Spam, Troll, etc.">
                            <input type="number" name="ls-jrs" class="expand" placeholder="Durée de la lecture seule, en jours" min="1">
                            {% csrf_token %}
                            <button type="submit" name="ls-temp">
                                {% trans "Confirmer" %}
                            </button>
                        </form>
                    </li>
                    <li>
                        <a href="#ls-{{ profile.pk }}" class="open-modal">
                            {% trans "Lecture seule" %}
                        </a>
                        <form action="{% url "member.views.modify_profile" profile.user.pk %}" method="post" id="ls-{{ profile.pk }}" class="modal modal-medium">
                            <p>
                                {% trans "Pour quelle raison souhaitez-vous mettre ce membre en lecture seule" %} ?
                            </p>
                            <input type="text" name="ls-text" class="expand" placeholder="Spam, Troll, etc.">
                            {% csrf_token %}
                            <button type="submit" name="ls">
                                {% trans "Confirmer" %}
                            </button>
                        </form>
                    </li>
                {% else %}
                    <li>
                        <a href="#ls-temp-{{ profile.pk }}" class="open-modal">
                            {% trans "Ôter la lecture seule" %}
                        </a>
                        <form action="{% url "member.views.modify_profile" profile.user.pk %}" method="post" id="ls-temp-{{ profile.pk }}" class="modal modal-medium">
                            <p>
                                {% blocktrans %}
                                Pour quelle raison souhaitez-vous <strong>lever la sanction</strong> de ce membre ?
                                {% endblocktrans %}
                            </p>
                            <input type="text" name="unls-text" class="expand" placeholder="Bonne actions ?">
                            {% csrf_token %}
                            <button type="submit" name="un-ls">
                                {% trans "Confirmer" %}
                            </button>
                        </form>
                    </li>
                {% endif %}

                {% if profile.can_read_now %}
                    <li>
                        <a href="#ban-temp-{{ profile.pk }}" class="open-modal">
                            {% trans "Bannir temporairement" %}
                        </a>
                        <form action="{% url "member.views.modify_profile" profile.user.pk %}" method="post" id="ban-temp-{{ profile.pk }}" class="modal modal-big">
                            <p>
                                {% blocktrans %}
                                    Pour quelle raison souhaitez-vous bannir ce membre <em>temporairement</em> ?
                                {% endblocktrans %}
                            </p>
                            <input type="text" name="ban-text" class="expand" placeholder="Spam, Troll, etc.">
                            <input type="number" name="ban-jrs" class="expand" placeholder="Durée du bannissement, en jours" min="1">
                            {% csrf_token %}
                            <button type="submit" name="ban-temp">
                                {% trans "Confirmer" %}
                            </button>
                        </form>
                    </li>
                    <li>
                        <a href="#ban-{{ profile.pk }}" class="open-modal">
                            {% trans "Bannir définitivement" %}
                        </a>
                        <form action="{% url "member.views.modify_profile" profile.user.pk %}" method="post" id="ban-{{ profile.pk }}" class="modal modal-small">
                            <p>
                                {% trans "Pour quelle raison souhaitez-vous bannir ce membre" %} ?
                            </p>
                            <input type="text" name="ban-text" class="expand" placeholder="Spam, Troll, etc.">
                            {% csrf_token %}
                            <button type="submit" name="ban">
                                {% trans "Confirmer" %}
                            </button>
                        </form>
                    </li>
                {% else %}
                    <li>
                        <a href="#unban-{{ profile.pk }}" class="open-modal">
                            {% trans "Ôter le bannissement" %}
                        </a>
                        <form action="{% url "member.views.modify_profile" profile.user.pk %}" method="post" id="unban-{{ profile.pk }}" class="modal modal-small">
                            <p>
                                {% trans "Pour quelle raison souhaitez vous lever la sanction de ce membre" %} ?
                            </p>
                            <input type="text" name="unban-text" class="expand" placeholder="Bonne action ?">
                            {% csrf_token %}
                            <button type="submit" name="un-ban">
                                {% trans "Confirmer" %}
                            </button>
                        </form>
                    </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}